In [44]:
import numpy as np

In [45]:
A = np.array([[3, 2], [4, 1]])

In [ ]:
autovalores, autovectores = np.linalg.eig(A)    

In [47]:
print("Autovalores:")
print(autovalores)
print("Autovectores:")
print(autovectores)

Autovalores:
[ 5. -1.]
Autovectores:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [48]:
autovectores

array([[ 0.70710678, -0.4472136 ],
       [ 0.70710678,  0.89442719]])

In [49]:
np.linalg.inv(autovectores)

array([[ 0.94280904,  0.47140452],
       [-0.74535599,  0.74535599]])

In [23]:
autovectores.T

array([[ 0.70710678,  0.70710678],
       [-0.4472136 ,  0.89442719]])

In [54]:
autovectores[:, 0] * autovalores[0]

array([3.53553391, 3.53553391])

In [52]:
autovectores[:, 1] @ autovectores[:, 0]

np.float64(0.3162277660168379)

In [53]:
np.dot(autovectores[:, 0], autovectores[:, 1])

np.float64(0.3162277660168379)

In [8]:
A_calc = autovectores @ np.diag(autovalores) @ np.linalg.inv(autovectores)
A_calc

array([[3., 2.],
       [4., 1.]])

## Matriz Simétrica

In [25]:
A = np.array([[3, 2], [2, 3]])
print(A==A.T)

[[ True  True]
 [ True  True]]


In [26]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [27]:
A_calc = autovectores @ np.diag(autovalores) @ autovectores.T
A_calc

array([[3., 2.],
       [2., 3.]])

In [33]:
np.linalg.inv(autovectores)

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [34]:
autovectores.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])