In [3]:
import numpy as np

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])  # Matriz 3x2
print("Matriz A:\n", A)
U, S, Vt = np.linalg.svd(A)  # Descomposición SVD

print("\nMatriz U:\n", U)
print("\nValores singulares:\n", S)
print("\nMatriz V transpuesta:\n", Vt)

Matriz A:
 [[1 2]
 [3 4]
 [5 6]]

Matriz U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Valores singulares:
 [9.52551809 0.51430058]

Matriz V transpuesta:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [2]:
sigma = np.zeros(A.shape)  # Matriz de ceros con el tamaño correcto
np.fill_diagonal(sigma, S)

A_calc = U @ sigma @ Vt
A_calc

array([[1., 2.],
       [3., 4.],
       [5., 6.]])