## Pseudoinversa de una matriz

In [1]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(suppress=True)

In [2]:
A = np.array([[2, 3], [5, 7], [11, 13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [7]:
U, D, V = np.linalg.svd(A)
print("\nU:\n", U)
print("\nD:\n", D)
print("\nV:\n", V)


U:
 [[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]

D:
 [19.40321383  0.71783924]

V:
 [[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [17]:
D_pse = np.zeros(A.shape).T
np.fill_diagonal(D_pse, 1/D)
D_pse

array([[0.05153785, 0.        , 0.        ],
       [0.        , 1.39306957, 0.        ]])

In [18]:
A_pse = V.T @ D_pse @ U.T
print("\nA_pse:\n", A_pse)


A_pse:
 [[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [25]:
np.linalg.pinv(A) @ A

array([[ 1., -0.],
       [ 0.,  1.]])